package com.treeliked.darkme2.model.dataobject;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class File {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.id
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_name
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_size
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    private String fileSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_bring_id
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    private String fileBringId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_bucket_id
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    private String fileBucketId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_save_days
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    private Integer fileSaveDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_attach
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    private String fileAttach;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_post_author
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    private String filePostAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_destination
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    private String fileDestination;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_post_date
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm",timezone = "GMT+8")
    private Date filePostDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.id
     *
     * @return the value of file.id
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.id
     *
     * @param id the value for file.id
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_name
     *
     * @return the value of file.file_name
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_name
     *
     * @param fileName the value for file.file_name
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_size
     *
     * @return the value of file.file_size
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    public String getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_size
     *
     * @param fileSize the value for file.file_size
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    public void setFileSize(String fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_bring_id
     *
     * @return the value of file.file_bring_id
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    public String getFileBringId() {
        return fileBringId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_bring_id
     *
     * @param fileBringId the value for file.file_bring_id
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    public void setFileBringId(String fileBringId) {
        this.fileBringId = fileBringId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_bucket_id
     *
     * @return the value of file.file_bucket_id
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    public String getFileBucketId() {
        return fileBucketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_bucket_id
     *
     * @param fileBucketId the value for file.file_bucket_id
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    public void setFileBucketId(String fileBucketId) {
        this.fileBucketId = fileBucketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_save_days
     *
     * @return the value of file.file_save_days
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    public Integer getFileSaveDays() {
        return fileSaveDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_save_days
     *
     * @param fileSaveDays the value for file.file_save_days
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    public void setFileSaveDays(Integer fileSaveDays) {
        this.fileSaveDays = fileSaveDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_attach
     *
     * @return the value of file.file_attach
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    public String getFileAttach() {
        return fileAttach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_attach
     *
     * @param fileAttach the value for file.file_attach
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    public void setFileAttach(String fileAttach) {
        this.fileAttach = fileAttach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_post_author
     *
     * @return the value of file.file_post_author
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    public String getFilePostAuthor() {
        return filePostAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_post_author
     *
     * @param filePostAuthor the value for file.file_post_author
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    public void setFilePostAuthor(String filePostAuthor) {
        this.filePostAuthor = filePostAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_destination
     *
     * @return the value of file.file_destination
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    public String getFileDestination() {
        return fileDestination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_destination
     *
     * @param fileDestination the value for file.file_destination
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    public void setFileDestination(String fileDestination) {
        this.fileDestination = fileDestination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_post_date
     *
     * @return the value of file.file_post_date
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    public Date getFilePostDate() {
        return filePostDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_post_date
     *
     * @param filePostDate the value for file.file_post_date
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    public void setFilePostDate(Date filePostDate) {
        this.filePostDate = filePostDate;
    }


    @Override
    public String toString() {
        return "File{" +
                "id='" + id + '\'' +
                ", fileName='" + fileName + '\'' +
                ", fileSize='" + fileSize + '\'' +
                ", fileBringId='" + fileBringId + '\'' +
                ", fileBucketId='" + fileBucketId + '\'' +
                ", fileSaveDays=" + fileSaveDays +
                ", fileAttach='" + fileAttach + '\'' +
                ", filePostAuthor='" + filePostAuthor + '\'' +
                ", fileDestination='" + fileDestination + '\'' +
                ", filePostDate=" + filePostDate +
                '}';
    }
}