package com.treeliked.darkme2.model.dataobject;

import java.util.Date;

public class Memo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memo.id
     *
     * @mbg.generated Sat Dec 22 11:01:22 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memo.memo_author
     *
     * @mbg.generated Sat Dec 22 11:01:22 CST 2018
     */
    private String memoAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memo.memo_title
     *
     * @mbg.generated Sat Dec 22 11:01:22 CST 2018
     */
    private String memoTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memo.memo_content
     *
     * @mbg.generated Sat Dec 22 11:01:22 CST 2018
     */
    private String memoContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memo.memo_type
     *
     * @mbg.generated Sat Dec 22 11:01:22 CST 2018
     */
    private Boolean memoType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memo.memo_state
     *
     * @mbg.generated Sat Dec 22 11:01:22 CST 2018
     */
    private Byte memoState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memo.memo_post_date
     *
     * @mbg.generated Sat Dec 22 11:01:22 CST 2018
     */
    private Date memoPostDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memo.id
     *
     * @return the value of memo.id
     *
     * @mbg.generated Sat Dec 22 11:01:22 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memo.id
     *
     * @param id the value for memo.id
     *
     * @mbg.generated Sat Dec 22 11:01:22 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memo.memo_author
     *
     * @return the value of memo.memo_author
     *
     * @mbg.generated Sat Dec 22 11:01:22 CST 2018
     */
    public String getMemoAuthor() {
        return memoAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memo.memo_author
     *
     * @param memoAuthor the value for memo.memo_author
     *
     * @mbg.generated Sat Dec 22 11:01:22 CST 2018
     */
    public void setMemoAuthor(String memoAuthor) {
        this.memoAuthor = memoAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memo.memo_title
     *
     * @return the value of memo.memo_title
     *
     * @mbg.generated Sat Dec 22 11:01:22 CST 2018
     */
    public String getMemoTitle() {
        return memoTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memo.memo_title
     *
     * @param memoTitle the value for memo.memo_title
     *
     * @mbg.generated Sat Dec 22 11:01:22 CST 2018
     */
    public void setMemoTitle(String memoTitle) {
        this.memoTitle = memoTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memo.memo_content
     *
     * @return the value of memo.memo_content
     *
     * @mbg.generated Sat Dec 22 11:01:22 CST 2018
     */
    public String getMemoContent() {
        return memoContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memo.memo_content
     *
     * @param memoContent the value for memo.memo_content
     *
     * @mbg.generated Sat Dec 22 11:01:22 CST 2018
     */
    public void setMemoContent(String memoContent) {
        this.memoContent = memoContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memo.memo_type
     *
     * @return the value of memo.memo_type
     *
     * @mbg.generated Sat Dec 22 11:01:22 CST 2018
     */
    public Boolean getMemoType() {
        return memoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memo.memo_type
     *
     * @param memoType the value for memo.memo_type
     *
     * @mbg.generated Sat Dec 22 11:01:22 CST 2018
     */
    public void setMemoType(Boolean memoType) {
        this.memoType = memoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memo.memo_state
     *
     * @return the value of memo.memo_state
     *
     * @mbg.generated Sat Dec 22 11:01:22 CST 2018
     */
    public Byte getMemoState() {
        return memoState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memo.memo_state
     *
     * @param memoState the value for memo.memo_state
     *
     * @mbg.generated Sat Dec 22 11:01:22 CST 2018
     */
    public void setMemoState(Byte memoState) {
        this.memoState = memoState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memo.memo_post_date
     *
     * @return the value of memo.memo_post_date
     *
     * @mbg.generated Sat Dec 22 11:01:22 CST 2018
     */
    public Date getMemoPostDate() {
        return memoPostDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memo.memo_post_date
     *
     * @param memoPostDate the value for memo.memo_post_date
     *
     * @mbg.generated Sat Dec 22 11:01:22 CST 2018
     */
    public void setMemoPostDate(Date memoPostDate) {
        this.memoPostDate = memoPostDate;
    }

    @Override
    public String toString() {
        return "Memo{" +
                "id='" + id + '\'' +
                ", memoAuthor='" + memoAuthor + '\'' +
                ", memoTitle='" + memoTitle + '\'' +
                ", memoContent='" + memoContent + '\'' +
                ", memoType=" + memoType +
                ", memoState=" + memoState +
                ", memoPostDate=" + memoPostDate +
                '}';
    }
}