package com.treeliked.darkme2.model.dataobject;

public class UserHandoffText {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_handoff_text.id
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_handoff_text.user_id
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_handoff_text.ptw_text
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    private String ptwText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_handoff_text.wtp_text
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    private String wtpText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_handoff_text.ptw_flag
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    private Byte ptwFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_handoff_text.wtp_flag
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    private Byte wtpFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_handoff_text.id
     *
     * @return the value of user_handoff_text.id
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_handoff_text.id
     *
     * @param id the value for user_handoff_text.id
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_handoff_text.user_id
     *
     * @return the value of user_handoff_text.user_id
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_handoff_text.user_id
     *
     * @param userId the value for user_handoff_text.user_id
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_handoff_text.ptw_text
     *
     * @return the value of user_handoff_text.ptw_text
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    public String getPtwText() {
        return ptwText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_handoff_text.ptw_text
     *
     * @param ptwText the value for user_handoff_text.ptw_text
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    public void setPtwText(String ptwText) {
        this.ptwText = ptwText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_handoff_text.wtp_text
     *
     * @return the value of user_handoff_text.wtp_text
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    public String getWtpText() {
        return wtpText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_handoff_text.wtp_text
     *
     * @param wtpText the value for user_handoff_text.wtp_text
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    public void setWtpText(String wtpText) {
        this.wtpText = wtpText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_handoff_text.ptw_flag
     *
     * @return the value of user_handoff_text.ptw_flag
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    public Byte getPtwFlag() {
        return ptwFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_handoff_text.ptw_flag
     *
     * @param ptwFlag the value for user_handoff_text.ptw_flag
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    public void setPtwFlag(Byte ptwFlag) {
        this.ptwFlag = ptwFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_handoff_text.wtp_flag
     *
     * @return the value of user_handoff_text.wtp_flag
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    public Byte getWtpFlag() {
        return wtpFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_handoff_text.wtp_flag
     *
     * @param wtpFlag the value for user_handoff_text.wtp_flag
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    public void setWtpFlag(Byte wtpFlag) {
        this.wtpFlag = wtpFlag;
    }
}