package com.treeliked.darkme2.model.dao;

import com.treeliked.darkme2.model.dataobject.UserHandoffText;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface UserHandoffTextMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_handoff_text
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    @Delete({
        "delete from user_handoff_text",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_handoff_text
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    @Insert({
        "insert into user_handoff_text (id, user_id, ",
        "ptw_text, wtp_text, ",
        "ptw_flag, wtp_flag)",
        "values (#{id,jdbcType=VARCHAR}, #{userId,jdbcType=VARCHAR}, ",
        "#{ptwText,jdbcType=VARCHAR}, #{wtpText,jdbcType=VARCHAR}, ",
        "#{ptwFlag,jdbcType=TINYINT}, #{wtpFlag,jdbcType=TINYINT})"
    })
    int insert(UserHandoffText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_handoff_text
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    @Select({
        "select",
        "id, user_id, ptw_text, wtp_text, ptw_flag, wtp_flag",
        "from user_handoff_text",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="ptw_text", property="ptwText", jdbcType=JdbcType.VARCHAR),
        @Result(column="wtp_text", property="wtpText", jdbcType=JdbcType.VARCHAR),
        @Result(column="ptw_flag", property="ptwFlag", jdbcType=JdbcType.TINYINT),
        @Result(column="wtp_flag", property="wtpFlag", jdbcType=JdbcType.TINYINT)
    })
    UserHandoffText selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_handoff_text
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    @Select({
        "select",
        "id, user_id, ptw_text, wtp_text, ptw_flag, wtp_flag",
        "from user_handoff_text"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="ptw_text", property="ptwText", jdbcType=JdbcType.VARCHAR),
        @Result(column="wtp_text", property="wtpText", jdbcType=JdbcType.VARCHAR),
        @Result(column="ptw_flag", property="ptwFlag", jdbcType=JdbcType.TINYINT),
        @Result(column="wtp_flag", property="wtpFlag", jdbcType=JdbcType.TINYINT)
    })
    List<UserHandoffText> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_handoff_text
     *
     * @mbg.generated Tue Dec 18 18:09:49 CST 2018
     */
    @Update({
        "update user_handoff_text",
        "set user_id = #{userId,jdbcType=VARCHAR},",
          "ptw_text = #{ptwText,jdbcType=VARCHAR},",
          "wtp_text = #{wtpText,jdbcType=VARCHAR},",
          "ptw_flag = #{ptwFlag,jdbcType=TINYINT},",
          "wtp_flag = #{wtpFlag,jdbcType=TINYINT}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(UserHandoffText record);
}